services:
  - type: web
    name: calligraphy-api
    env: python
    plan: free
    buildCommand: |
      echo "python-3.11.9" > runtime.txt
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: -r requirements.txt
    startCommand: python server.py
