services:
  - type: web
    name: calligraphy-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    autoDeploy: true
buildCommand: pip install --only-binary=:all: -r requirements.txt
